server:
 port: 8002
spring:
 datasouce:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
  username: sa
  password: 
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:2000/eureka
  healthchecks:
   enabled: true